spring.application.name=food-management-system
server.port=8084

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:food-management.db

logging.level.root=INFO
logging.level.com.example.foodmanagement=DEBUG
